version: '3.8'
services:

  db:
    image: postgres:14-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
      - POSTGRES_DB=shareit
    hostname: db

  server:
    build: server
    image: shareit_server_image
    container_name: shareit_server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVER_PORT=9090

  gateway:
    build: gateway
    image: shareit_gateway_image
    container_name: shareit_gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - GATEWAY_PORT=8080